### ISSUE TITLE
IDEA 部署到Tomcat运行报错

### ISSUE THREAD

**Issue by sunlewuyou** [ushelp/EasyEE#10]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in file [D:\DevelopTools\JetBrains\IdeaProjects\easyee-sh\target\easyee-sh\WEB-INF\classes\spring\ApplicationContext_dao.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: TRACE

截取了上面这个最下面的异常，请问为何只能通过运行start.bat运行项目？还有Oracle的项目主键生成策略要改一下。默认的是MySQL，希望在文档里注明一下，方便新手，谢谢，希望采纳完善！

**Comment by ushelp** [comment]
@sunlewuyou 升级 Hibernate 后导致了一个日志包冲突问题，现已修复，请使用 4.4.0.
