### ISSUE TITLE
关于CKFinder相关Jar

### ISSUE THREAD

**Issue by xiaozhu5615** [ushelp/EasyEE#11]
因为在maven里面找不到，但是看到项目里放到lib里面的包，我实在看不惯，原谅我的强迫症，于是我决定把这些相关jar放到maven本地库中，代码贴在下面，如果有冒犯请原谅。
mvn install:install-file -Dfile=CKFinderPlugin-FileEditor-2.6.2.1.jar -DgroupId=com.ckfinder -DartifactId=CKFinderPlugin-FileEditor -Dversion=2.6.2.1 -Dpackaging=jar

mvn install:install-file -Dfile=CKFinderPlugin-ImageResize-2.6.2.1.jar -DgroupId=com.ckfinder -DartifactId=CKFinderPlugin-ImageResize -Dversion=2.6.2.1 -Dpackaging=jar

mvn install:install-file -Dfile=CKFinderPlugin-Watermark-2.6.2.1.jar -DgroupId=com.ckfinder -DartifactId=CKFinderPlugin-Watermark -Dversion=2.6.2.1 -Dpackaging=jar

mvn install:install-file -Dfile=CKFinder-2.6.2.1.jar -DgroupId=com.ckfinder -DartifactId=CKFinder -Dversion=2.6.2.1 -Dpackaging=jar

**Comment by ushelp** [comment]
@xiaozhu5615 
感谢你的工作，方便的话可以改一下 POM，再项目根目录加入 install 安装命令文件，发一个 PR。

**Comment by xiaozhu5615** [comment]
忘了说，我使用的sm-spring-boot项目
抱歉忘记贴pom.xml增加内容
 
		<dependency>
			 <groupId>com.ckfinder</groupId>
			<artifactId>CKFinderPlugin-FileEditor</artifactId>
			<version>2.6.2.1</version>
		</dependency>

		<dependency>
			<groupId>com.ckfinder</groupId>
			<artifactId>CKFinderPlugin-ImageResize</artifactId>
			<version>2.6.2.1</version>
		</dependency>

		<dependency>
			<groupId>com.ckfinder</groupId>
			<artifactId>CKFinderPlugin-Watermark</artifactId>
			<version>2.6.2.1</version>
		</dependency>

		<dependency>
			<groupId>com.ckfinder</groupId>
			<artifactId>CKFinder</artifactId>
			<version>2.6.2.1</version>
		</dependency>

**Comment by ushelp** [comment]
@xiaozhu5615 
谢谢。 
已更新至 4.4.0-RELEASE_fixed.3
添加了  `Maven local artifact install`  目录。
