### ISSUE TITLE
BUG BaseController 中的setJsonMsgMap方法

### ISSUE THREAD

**Issue by RozwelGustab** [ushelp/EasyEE#3]
`for (int i = 0; i < jsonKeyAndValuePair.length / 2; i++) {
				jsonMap.put(jsonKeyAndValuePair[i], jsonKeyAndValuePair[2 * i + 1]);
			}`
如果输入 k1,v1,k2,v2,k3,v3返回的结果是
k1=v1, k2=v3, v1=v2

应该改成
`for (int i = 0; i < jsonKeyAndValuePair.length-1; i=i+2) {
                jsonMap.put(jsonKeyAndValuePair[i], jsonKeyAndValuePair[i + 1]);
            }`

**Comment by ushelp** [comment]
@RozwelGustab 感谢你的反馈。 Bug 已经确认修改。

```JAVA
for (int i = 0; i < jsonKeyAndValuePair.length / 2; i++) {
	jsonMap.put(jsonKeyAndValuePair[2 * i], jsonKeyAndValuePair[2 * i + 1]);
}
```
