### ISSUE TITLE
【BUG】刷新标签 旧的标签未销毁

### ISSUE THREAD

**Issue by RozwelGustab** [ushelp/EasyEE#4]
1、关闭一个标签 重新打开这个标签
2、刷新一个标签
这两种情况都会导致页面上重新加载标签中的代码，但是旧的标签并未销毁。
比如在线demo中的员工信息管理，关闭再打开的时候，未销毁empContextMenu
刷新的时候empEditDialog和empContextMenu均未销毁。

**Comment by ushelp** [comment]
你好，

感谢反馈。框架前端使用的 EasyUIEx 是实现了在 EasyUI 中刷新和关闭标签时主动销毁内部相应的 Dialog 的功能的。

经过我在本地的测试（Firefox, Chrome），并未出现刷新或关闭后 Dialog 依然存在的问题。

但是之前没有处理 ContextMenu 右键菜单的销毁，所以这个问题会尽快解决。

如果你有具体测试图片，可以发给我，以便判断。

http://easyproject.cn 

< RozwelGustab> 在 2017-04-27 14

**Comment by ushelp** [comment]
@RozwelGustab 

现在发布了 https://github.com/ushelp/EasyEE/releases/tag/4.2.0-RELEASE_fixed.4 版本。
 EasyUIEX 更新到 easy.easyuiex.min-2.2.4.js
 版本 https://github.com/ushelp/EasyUIEx/releases/tag/2.2.4-RELEASE 。仅需更换JS 文件。

您可以试试问题是否解决。

**Comment by RozwelGustab** [comment]
感谢 更新之后ContextMenu已经正常销毁了  dialog未销毁的问题也没有再重现
