### ISSUE TITLE
8080端口无法关闭 同时监听了两个端口？

### ISSUE THREAD

**Issue by RozwelGustab** [ushelp/EasyEE#5]
server.port=9999
端口号已经设置为9999
但是启动的时候：Tomcat started on port(s): 8080 (http) 9999 (http)
用8080以及9999都能够访问到项目
求解，这个8080怎么才能关掉，因为其他程序有占用这个端口，每次启动的时候不关闭其他程序的话就会提示 Address already in use: JVM_Bind。

**Comment by ushelp** [comment]
@RozwelGustab 
你好，请问是哪个项目，请检查 POM 文件 或 SpringBoot 的启动类和配置，是否同时启动了 Tomcat 和 Jetty.

**Comment by RozwelGustab** [comment]
@ushelp  抱歉忘记说明了 
easyee-sh-springboot
pom文件只进行了数据库的修改由mysql改为了postgresql，其他和github上是一样的。
使用jetty时启动正常，只监听了9999一个端口，
但是使用tomcat时（已经把jetty相关的依赖都删了）会启动8080和9999两个端口。

**Comment by RozwelGustab** [comment]
@ushelp 刚刚再试了一次 是tomcat的问题
easyee-sh-springboot使用的是8.5.8的版本 启动的时候监听了两个端口
我改为8.5.15就没问题了 只监听了一个端口
建议这边也更新一下tomcat的版本吧

**Comment by ushelp** [comment]
@RozwelGustab 感谢反馈。稍后会更新新版本。
