### ISSUE TITLE
【BUG】EasyUIEx的右键菜单bug

### ISSUE THREAD

**Issue by RozwelGustab** [ushelp/EasyEE#6]
BUG1、比如http://www.easyproject.cn/easyee/toMain中的用户管理
datagrid中的数据和分页栏间有空白的部分，右键此空白部分之后，这个右键菜单就再也无法点出来了。
uiEx.js中的showDatagridContextMenu/showTreegridContextMenu方法应该加上if (index != -1) 的判断。

BUG2、打开三个标签页，右键其中一个，选择关闭其他，然后这个右键菜单再也无法点出。（已经被销毁）
大概看了一下，是在uiEx.js中的destoryTab方法里将所有的easyui-menu类遍历了一次，不包含在uiEx.globalContextMenuMap中的就销毁掉，但是忘记了还有tabsMenu这个公用的菜单，判断方法应该加上this.id!='tabsMenu'。

**Comment by ushelp** [comment]
@RozwelGustab  感谢你的反馈。稍后会修改更新。

**Comment by ushelp** [comment]
@RozwelGustab 再次感谢你详细的 Bug 反馈，问题已经修复。
