### ISSUE TITLE
showTreegridContextMenu index未定义

### ISSUE THREAD

**Issue by RozwelGustab** [ushelp/EasyEE#7]
showTreegridContextMenu = function (e, row) {
            if (index != -1) {
                $(this).treegrid('select', row.id);
                $($(this).treegrid('options').menuSelector).menu('show', {
                    left: e.pageX,
                    top: e.pageY
                });
            }
        },

**Comment by ushelp** [comment]
@RozwelGustab 已确认。

**Comment by ushelp** [comment]
@RozwelGustab 近期工作繁忙，加了參數，剛剛修復，見諒。
