### ISSUE TITLE
运行前修改SysOperationPermissionDAO.xml

### ISSUE THREAD

**Issue by ss2468776986** [ushelp/EasyEE#9]
运行前需要把SysOperationPermissionDAO.xml中id="getAllOpreationNames的sql语句所有表名改为小写（如Sys_Operation改为sys_operation），否则项目部署后无论哪个账号都会登录失败

**Comment by ushelp** [comment]
您好，这可能是 mysql 在 linux 下配置模式的的问题，可在mysql配置文件中加入：
` lower_case_table_names=1`
重启 MySQL 即可。
